[project]
name = "kemm30"
version = "0.1.0"
description = "KEMM30 uv environment for easier installation of packages"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "biopython==1.79",
    "brewer2mpl==1.4.1",
    "ffmpeg>=1.1",
    "ipympl==0.9",
    "ipywidgets==7.7.2",
    "lmfit==1.0.3",
    "lxml==4.3",
    "matplotlib==3.4.0",
    "mdtraj>=1.8",
    "nglview>=3.0",
    "nmrglue",
    "numpy==1.18",
    "openpyxl==3",
    "pandas==1.1",
    "scipy==1.4",
]

[tool.uv.sources]
nmrglue = { git = "https://github.com/jjhelmus/nmrglue" }
